# Generated by Django 3.2.13 on 2022-06-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_post_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
