# Generated by Django 3.2.13 on 2022-06-03 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220602_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
