# Generated by Django 3.2.13 on 2022-06-09 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_new_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='new',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
