# Generated by Django 2.2 on 2022-06-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20220609_1106'),
        ('website', '0007_contact_alter_new_id'),
    ]

    operations = [
    ]
